name: webserial
description: WebSerial support for Dart built on the web package.
version: 1.1.0
repository: https://github.com/maks/dart_webserial

environment:
  sdk: ^3.5.1

dependencies:
  web: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
